# `EleutherAI/gpt-neo-125m`

https://huggingface.co/EleutherAI/gpt-neo-125m

In [ ]:
from transformers import pipeline
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-125M')
generator("EleutherAI has", do_sample=True, min_length=20)


In [4]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name="EleutherAI/gpt-neo-125M"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

In [6]:
#print(model)

In [7]:
model.config

GPTNeoConfig {
  "_attn_implementation_autoset": true,
  "_name_or_path": "EleutherAI/gpt-neo-125M",
  "activation_function": "gelu_new",
  "architectures": [
    "GPTNeoForCausalLM"
  ],
  "attention_dropout": 0,
  "attention_layers": [
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local"
  ],
  "attention_types": [
    [
      [
        "global",
        "local"
      ],
      6
    ]
  ],
  "bos_token_id": 50256,
  "classifier_dropout": 0.1,
  "embed_dropout": 0,
  "eos_token_id": 50256,
  "gradient_checkpointing": false,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": null,
  "layer_norm_epsilon": 1e-05,
  "max_position_embeddings": 2048,
  "model_type": "gpt_neo",
  "num_heads": 12,
  "num_layers": 12,
  "resid_dropout": 0,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",


In [8]:
text = "I think I will go live under the"
encoded_input = tokenizer(text, return_tensors='pt')

for k in encoded_input:
    print(k)
    print(encoded_input[k].shape)
    print(encoded_input[k])


input_ids
torch.Size([1, 8])
tensor([[  40,  892,  314,  481,  467, 2107,  739,  262]])
attention_mask
torch.Size([1, 8])
tensor([[1, 1, 1, 1, 1, 1, 1, 1]])


In [9]:
model.eval()
with torch.no_grad():
    output = model(encoded_input['input_ids'])

print(output.logits.shape)
print(output.logits)

torch.Size([1, 8, 50257])
tensor([[[ -7.9161,  -5.5552,  -7.7819,  ..., -16.8574, -11.3657,  -7.8918],
         [ -6.6331,  -5.6495, -12.9270,  ..., -15.4003, -14.9996,  -8.6412],
         [-14.9640,  -8.0909, -15.2132,  ..., -16.7484, -13.8357, -14.1348],
         ...,
         [ -3.8692,  -5.7102, -10.8259,  ..., -15.3034, -15.8766, -10.8813],
         [ -4.7259,  -5.1645,  -8.1540,  ..., -12.3549,  -9.6523,  -5.7281],
         [ -9.0182,  -9.2727,  -6.7630,  ..., -14.4963, -10.8874,  -7.4265]]])


In [10]:
logits = output.logits
probs = torch.softmax(logits,dim=-1)
out_ids = torch.argmax(probs, dim=-1)
out_ids

tensor([[ 423,  340, 1101,  307,  284,  287,  262, 7696]])

In [12]:
out_text = tokenizer.decode(out_ids.squeeze(0).tolist())
out_text

" have it'm be to in the bridge"

In [14]:
# Another way for output seems to be 
text = "I think I will go live under the"
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
logits = output.logits
probs = torch.softmax(logits,dim=-1)
out_ids = torch.argmax(probs, dim=-1)
out_text = tokenizer.decode(out_ids.squeeze(0).tolist())
out_text


" have it'm be to in the bridge"

In [15]:
# shortcut generate function to generate multiple tokens

output = model.generate(**encoded_input, max_length=50)
print(tokenizer.decode(output[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


I think I will go live under the bridge. I have a lot of friends who are going to be there. I have a lot of friends who are going to be there. I have a lot of friends who are going to be there. I
