# Lets see how the GPT2 we constucted compares with GPT on Huggingface

## `GPT2LMHeadModel`

In [10]:
import torch
from transformers import GPT2Tokenizer, GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2LMHeadModel.from_pretrained('gpt2')

In [11]:
#print(model)

In [12]:
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt')

for k in encoded_input:
    print(k)
    print(encoded_input[k].shape)
    print(encoded_input[k])


input_ids
torch.Size([1, 10])
tensor([[3041, 5372,  502,  416,  597, 2420,  345, 1549,  588,   13]])
attention_mask
torch.Size([1, 10])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [13]:
model.eval()
with torch.no_grad():
    output = model(encoded_input['input_ids'])

print(output.logits.shape)
print(output.logits)

torch.Size([1, 10, 50257])
tensor([[[ -28.7086,  -27.9282,  -30.2393,  ...,  -37.6027,  -35.8095,
           -28.8439],
         [ -60.0999,  -57.8383,  -62.0975,  ...,  -68.0317,  -67.7715,
           -60.5209],
         [ -76.6621,  -78.3350,  -83.4316,  ...,  -89.8897,  -89.1758,
           -81.1512],
         ...,
         [-145.1963, -145.4156, -150.1035,  ..., -153.6665, -150.1051,
          -146.9225],
         [ -84.2475,  -85.6010,  -91.2381,  ...,  -99.5435,  -97.8361,
           -88.2612],
         [-122.2600, -121.1204, -121.5651,  ..., -131.8222, -131.5997,
          -115.1341]]])


In [14]:
logits = output.logits
probs = torch.softmax(logits,dim=-1)
out_ids = torch.argmax(probs, dim=-1)
out_ids

tensor([[  13,  262,  351,  257, 1724,   11,  765,  588,   13,  198]])

In [15]:
out_text = tokenizer.decode(out_ids.squeeze(0).tolist())
out_text

'. the with a means, want like.\n'

In [16]:
# shortcut generate function
text = "I love to code. But often I have to get up from chair.  I hate that."
encoded_input = tokenizer(text, return_tensors='pt')

output = model.generate(**encoded_input, max_length=50)
print(tokenizer.decode(output[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


I love to code. But often I have to get up from chair.  I hate that.  I hate that I have to do this.  I hate that I have to do this.  I hate that I have to do this.
